name: Publish To Rubygems

on:
  push:
    branches:
      - "main"
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: cadwallion/publish-rubygems-action@master
        env:
          GIT_AUTHOR_EMAIL: ${{secrets.EMAIL}}
          GIT_AUTHOR_NAME: ${{secrets.NAME}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release
