name: Publish To Rubygems

on:
  push:
    branches:
      - "main"
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
              git config --global user.email "spam@flinkwise.com"
              git config --global user.name "master"

      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: cadwallion/publish-rubygems-action@master
        env:
          GIT_AUTHOR_EMAIL: "spam@flinkwise.com"
          GIT_AUTHOR_NAME: "master"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release
